/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : hncw
 * Created : 01/13/2015 10:25:34
 */

package com.aicai.service.login.dao.memberImp;

import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.aicai.service.login.dao.memberImp.ZZfd;



public class ZZfd {

	private String hghj;

	/**
	 *
	 * getter method for hghj
	 * @return
	 *
	 */
	public String getHghj() {
		
		return this.hghj;
	}

	/**
	 *
	 * setter method for hghj
	 * @param hghj
	 *
	 */
	public void setHghj(final String hghj) {
		this.hghj = hghj;
	}

	
}
